# Generated by Django 5.2.5 on 2025-10-21 11:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylocation',
            name='closing_time',
            field=models.TimeField(default=datetime.time(2, 0)),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='genre',
            field=models.CharField(choices=[('HIPHOP', 'Hip Hop/R&B'), ('AFROBEAT', 'Afrobeat'), ('ELECTRONIC', 'Electronic/Dance'), ('ROCK', 'Rock'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='opening_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='price_tier',
            field=models.CharField(choices=[('$', 'Cheap'), ('$$', 'Moderate'), ('$$$', 'Expensive')], default='$', max_length=3),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='stories/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('party_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='core.partylocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('current_tier', models.CharField(default='Newcomer', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.partylocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_check_in')],
            },
        ),
    ]
