# Generated by Django 5.2.5 on 2025-11-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement_eventinvite_friendship_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylocation',
            name='average_rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='current_crowd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='total_checkins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partylocation',
            name='vibe_level',
            field=models.CharField(choices=[('CHILL', 'Chill'), ('MEDIUM', 'Medium'), ('HIGH', 'High Energy')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('MUSIC', 'Music'), ('FESTIVAL', 'Festival'), ('CLUB', 'Club Night'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('OTHER', 'Other')], default='MUSIC', max_length=20)),
                ('price_tier', models.CharField(choices=[('$', 'Cheap (Under 20K)'), ('$$', 'Moderate (20K-50K)'), ('$$$', 'Expensive (50K+)')], default='$', max_length=3)),
                ('expected_attendees', models.IntegerField(default=0)),
                ('actual_attendees', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('party_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.partylocation')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CHECKIN', 'User Check-in'), ('VIDEO', 'Video Upload'), ('EVENT', 'New Event'), ('RSVP', 'Event RSVP'), ('REVIEW', 'Location Review')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('party_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partylocation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOING', 'Going'), ('INTERESTED', 'Interested'), ('NOT_GOING', 'Not Going')], default='INTERESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
